services:
  - type: web
    name: interview-mate-api
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false